import Foundation

extension Notification.Name {
    static let languageDidChange = Notification.Name("MaosRec.languageDidChange")
}

final class L10n {
    static let shared = L10n()

    private let strings: [String: [String: String]] = [
        "en": [
            "app.subtitle": "Lightweight screen recorder",
            "brand.tagline": "Simple. Fast. For macOS.",
            "nav.record": "Record",
            "nav.camera": "Camera",
            "nav.audio": "Audio",
            "nav.settings": "Settings",
            "nav.help": "Help",
            "nav.language": "Language",
            "nav.about": "About",
            "source.heading": "Source",
            "panel.record": "Record",
            "mode.screen": "Screen",
            "mode.window": "Window",
            "mode.area": "Area",
            "field.screen": "Screen",
            "field.window": "Window",
            "field.camera": "Camera",
            "field.microphone": "Microphone",
            "field.format": "Format",
            "field.quality": "Quality",
            "source.none.camera": "Not selected",
            "source.none.mic": "Not selected",
            "source.entire": "Entire screen",
            "source.noWindow": "No window",
            "format.mp4": "MP4 (H.264, AAC)",
            "quality.economy.menu": "Economy (540p, 12 FPS)",
            "quality.balanced.menu": "Balanced (720p, 15 FPS)",
            "quality.smooth.menu": "Smooth (720p, 30 FPS)",
            "area.hint": "Drag across the frame to choose an area.",
            "window.hint": "Choose a window in the list. Its picture is not loaded, to save memory.",
            "help.body": "Maos Record records the selected display to an MP4 file. The picture in the window is drawn, not captured, so the app stays light. Camera and microphone are recorded only when you select them. On a slow Mac, keep Economy quality.",
            "about.version": "Version %@",
            "about.system": "For macOS 10.15 and later",
            "audio.page": "Choose the microphone on the Record screen. macOS 10.15 cannot capture system audio directly.",
            "camera.page": "Choose the camera on the Record screen. Here you set where the small overlay sits.",
            "source.screen": "SCREEN",
            "source.camera": "Camera overlay",
            "source.audio": "Microphone",
            "source.part.screen": "Screen",
            "source.part.camera": "Camera",
            "source.part.audio": "Audio",
            "record.ready.sources": "Ready · %@",
            "source.display": "Display",
            "source.device": "Device",
            "source.off": "Off",
            "preview.title": "Recording preview",
            "preview.hint": "The live screen preview is disabled to save memory.",
            "preview.camera": "CAMERA",
            "record.start": "Start recording",
            "record.stop": "Stop recording",
            "record.preparing": "Preparing…",
            "record.saving": "Saving…",
            "record.ready": "Ready",
            "record.elapsed": "Recording  %@",
            "record.saved": "Recording saved",
            "record.error": "Could not record",
            "record.permission": "Allow Screen Recording in System Preferences → Security & Privacy, then restart Maos Record.",
            "record.devicePermission": "Camera or microphone access was denied. Allow access in System Preferences → Security & Privacy.",
            "error.display": "The selected display is no longer available.",
            "error.screenInput": "The screen capture input could not be created.",
            "error.output": "The capture output could not be created.",
            "error.camera": "The selected camera is unavailable.",
            "error.microphone": "The selected microphone is unavailable.",
            "settings.title": "Settings",
            "settings.general": "General",
            "settings.language": "Language",
            "settings.language.auto": "System language",
            "settings.language.en": "English",
            "settings.language.ru": "Russian",
            "settings.output": "Save recordings to",
            "settings.choose": "Choose…",
            "settings.theme": "Theme",
            "settings.theme.system": "System (light or dark), solid background",
            "settings.quality": "Recording quality",
            "settings.quality.economy": "Economy — 540p, 12 fps",
            "settings.quality.balanced": "Balanced — 720p, 15 fps",
            "settings.quality.smooth": "Smooth — 720p, 30 fps",
            "settings.minimize": "Minimize the window when recording starts",
            "settings.updates": "Updates",
            "settings.autoUpdates": "Automatically check for and install updates",
            "settings.check": "Check now",
            "camera.position": "Position",
            "camera.size": "Size",
            "camera.topLeft": "Top left",
            "camera.topRight": "Top right",
            "camera.bottomLeft": "Bottom left",
            "camera.bottomRight": "Bottom right",
            "menu.file": "File",
            "menu.settings": "Settings…",
            "menu.updates": "Check for Updates…",
            "menu.quit": "Quit Maos Record",
            "menu.showFile": "Show in Finder",
            "alert.ok": "OK"
        ],
        "ru": [
            "app.subtitle": "Лёгкая запись экрана",
            "brand.tagline": "Simple. Fast. For macOS.",
            "nav.record": "Запись",
            "nav.camera": "Камера",
            "nav.audio": "Аудио",
            "nav.settings": "Настройки",
            "nav.help": "Помощь",
            "nav.language": "Язык",
            "nav.about": "О приложении",
            "source.heading": "Источник",
            "panel.record": "Запись",
            "mode.screen": "Экран",
            "mode.window": "Окно",
            "mode.area": "Область",
            "field.screen": "Экран",
            "field.window": "Окно",
            "field.camera": "Камера",
            "field.microphone": "Микрофон",
            "field.format": "Формат",
            "field.quality": "Качество",
            "source.none.camera": "Не выбрана",
            "source.none.mic": "Не выбран",
            "source.entire": "Весь экран",
            "source.noWindow": "Нет окон",
            "format.mp4": "MP4 (H.264, AAC)",
            "quality.economy.menu": "Экономное (540p, 12 FPS)",
            "quality.balanced.menu": "Баланс (720p, 15 FPS)",
            "quality.smooth.menu": "Плавное (720p, 30 FPS)",
            "area.hint": "Потяните по кадру, чтобы выбрать область.",
            "window.hint": "Выберите окно в списке. Его картинка не загружается, чтобы не занимать память.",
            "help.body": "Maos Record записывает выбранный монитор в MP4. Картинка в окне нарисована, а не захвачена с экрана, поэтому программа остаётся лёгкой. Камера и микрофон пишутся только если вы их выбрали. На слабом Mac оставьте качество «Экономное».",
            "about.version": "Версия %@",
            "about.system": "Для macOS 10.15 и новее",
            "audio.page": "Микрофон выбирается на экране «Запись». macOS 10.15 не даёт напрямую записывать системный звук.",
            "camera.page": "Камера выбирается на экране «Запись». Здесь задаётся положение маленького окна камеры.",
            "source.screen": "ЭКРАН",
            "source.camera": "Камера поверх",
            "source.audio": "Микрофон",
            "source.part.screen": "Экран",
            "source.part.camera": "Камера",
            "source.part.audio": "Звук",
            "record.ready.sources": "Готово · %@",
            "source.display": "Монитор",
            "source.device": "Устройство",
            "source.off": "Выкл.",
            "preview.title": "Предпросмотр записи",
            "preview.hint": "Живой предпросмотр экрана отключён для экономии памяти.",
            "preview.camera": "КАМЕРА",
            "record.start": "Начать запись",
            "record.stop": "Остановить запись",
            "record.preparing": "Подготовка…",
            "record.saving": "Сохранение…",
            "record.ready": "Готово",
            "record.elapsed": "Идёт запись  %@",
            "record.saved": "Запись сохранена",
            "record.error": "Не удалось записать",
            "record.permission": "Разрешите «Запись экрана» в Системных настройках → Защита и безопасность, затем перезапустите Maos Record.",
            "record.devicePermission": "Нет доступа к камере или микрофону. Разрешите доступ в Системных настройках → Защита и безопасность.",
            "error.display": "Выбранный монитор больше недоступен.",
            "error.screenInput": "Не удалось создать источник записи экрана.",
            "error.output": "Не удалось создать выход записи.",
            "error.camera": "Выбранная камера недоступна.",
            "error.microphone": "Выбранный микрофон недоступен.",
            "settings.title": "Настройки",
            "settings.general": "Основные",
            "settings.language": "Язык",
            "settings.language.auto": "Язык системы",
            "settings.language.en": "English",
            "settings.language.ru": "Русский",
            "settings.output": "Сохранять записи в",
            "settings.choose": "Выбрать…",
            "settings.theme": "Тема",
            "settings.theme.system": "Системная (светлая или тёмная), без прозрачности",
            "settings.quality": "Качество записи",
            "settings.quality.economy": "Экономное — 540p, 12 кадр/с",
            "settings.quality.balanced": "Баланс — 720p, 15 кадр/с",
            "settings.quality.smooth": "Плавное — 720p, 30 кадр/с",
            "settings.minimize": "Сворачивать окно после начала записи",
            "settings.updates": "Обновления",
            "settings.autoUpdates": "Автоматически проверять и устанавливать обновления",
            "settings.check": "Проверить сейчас",
            "camera.position": "Положение",
            "camera.size": "Размер",
            "camera.topLeft": "Слева сверху",
            "camera.topRight": "Справа сверху",
            "camera.bottomLeft": "Слева снизу",
            "camera.bottomRight": "Справа снизу",
            "menu.file": "Файл",
            "menu.settings": "Настройки…",
            "menu.updates": "Проверить обновления…",
            "menu.quit": "Завершить Maos Record",
            "menu.showFile": "Показать в Finder",
            "alert.ok": "ОК"
        ]
    ]

    var languageCode: String {
        switch Preferences.language {
        case .english: return "en"
        case .russian: return "ru"
        case .automatic:
            return Locale.preferredLanguages.first?.lowercased().hasPrefix("ru") == true ? "ru" : "en"
        }
    }

    func string(_ key: String) -> String {
        strings[languageCode]?[key] ?? strings["en"]?[key] ?? key
    }

    func setLanguage(_ language: AppLanguage) {
        Preferences.language = language
        NotificationCenter.default.post(name: .languageDidChange, object: nil)
    }
}

func tr(_ key: String) -> String { L10n.shared.string(key) }
